services:
  springboot:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: my_springboot_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.17.0.2:5432/cbstlo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret
    ports:
      - "8080:8080"
    networks:
      - backend-network

networks:
  backend-network:
