services:
  postgres:
    image: postgres:16
    container_name: appdubleu-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: cbstlo
    ports:
      - "5432:5432"
    networks:
      - backend-network

  springboot:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: appdubleu-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://appdubleu-postgres:5432/cbstlo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret
    ports:
      - "8080:8080"
    networks:
      - backend-network
    depends_on:
      - postgres

networks:
  backend-network:
